name: CI/CD
on:
  push:
    tags: v*

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build and Pack NuGet package
        run: dotnet pack BindingHelper/BindingHelper.csproj -p:Version='${{ steps.gitversion.outputs.SemVer }}' -c Release
      
      - name: Upload NuGet package to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: nugetPackage
          path: bin/Release/ 
