name: CI/CD
on:
  push:
    tags: v*

#env:
#  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
#  DOTNET_NOLOGO: true
#  NuGetDirectory: ${{ github.workspace}}/nuget


jobs: 
 build:
    runs-on: windows-2019
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    #- name: Restore nuget packages
    #  run: nuget restore -ConfigFile ./NuGet.Config BindingHelper.sln
      
    # Create the NuGet package in the folder from the environment variable NuGetDirectory
    #- run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}

    #- run: cd ${{ github.workspace }}

    - run: nuget pack BindingHelper/BindingHelper.csproj
