name: CI/CD
on:
  push:
    tags: v*

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      #Build/pack the project
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/donpp237/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.TOKEN}}
          
      - name: Build solution and generate NuGet package
        run: |  
          cd BindingHelper
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./BindingHelper/out/*.nupkg --skip-duplicate --no-symbols true
