name: CI/CD
on:
  push:
    tags: v*

jobs: 
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@main

      #Build/pack the project
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup .nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
          
      - name: Build project
        run: dotnet build -c Release

      #- name: Generate a NuGet package
      #  run: dotnet pack --no-build -c Release -o .

      #- name: Echo
      #  run: echo $GITHUB_WORKSPACE/BindingHelper
      
      - name: Navigate
        run: cd $GITHUB_WORKSPACE

      #- name: ECHO
      #  run: echo `ls -al`

      - name: Nuget Package
        #run: dotnet pack $GITHUB_WORKSPACE/BindingHelper/BindingHelper.csproj
        run: dotnet pack

      - name: Push to GitHub package registry
        run: dotnet nuget push *.nupkg
