name: CI/CD
on:
  push:
    tags: v*

jobs: 
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@main

      #Build/pack the project
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '4.6.1'
          source-url: https://nuget.pkg.github.com/donpp237/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.TOKEN}}
          
      - name: Build project
        run: dotnet build -c Release

      - name: Generate a NuGet package
        run: dotnet pack --no-build -c Release -o .

      - name: Push to GitHub package registry
        run: dotnet nuget push *.nupkg
