name: CI/CD
on:
  push:
    tags: v*

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      #Build/pack the project
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Build and Pack NuGet package
        run: dotnet pack -o ..\..\src\BindingHelper\BindingHelper.csproj -p:Version='${{ steps.gitversion.outputs.SemVer }}' -c Release

      - name: Upload NuGet package to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: nugetPackage
          path: bin/Release/ 
