name: CI/CD
on:
  push:
    tags: v*

jobs: 
 build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    #- name: Restore nuget packages
    #  run: nuget restore -ConfigFile ./NuGet.Config juliet.sln
      
    # Create the NuGet package in the folder from the environment variable NuGetDirectory
    - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
