name: CI/CD
on:
  push:
    tags: v*

jobs: 
  create_nuget:
    runs-on: [ self-hosted, vs2022 ]
    steps:
    - uses: actions/checkout@v4

    # Install the .NET SDK indicated in the global.json file
    - name: Setup .NET
      uses: actions/setup-dotnet@v1

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Restore nuget packages
      run: nuget restore -ConfigFile ./NuGet.Config juliet.sln
      
    # Create the NuGet package in the folder from the environment variable NuGetDirectory
    - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
